
name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this if your main branch is named 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true # Set to true if your Hugo theme is a Git submodule
          fetch-depth: 0    # Fetch all history for .GitInfo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # You can specify a specific Hugo version if needed, e.g., '0.121.1'

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' # Adjust this if your main branch is named 'master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: cravey.dev # Add this line if you are using a custom domain (like cravey.dev)
